kind: pipeline
type: docker
name: default

steps:
- name: test
  image: xyzuan/xdocker
  environment:
    BOT_TOKEN:
      from_secret: BOT_TOKEN
  commands:
  - git clone https://github.com/rama982/kernel_xiaomi_beryllium --depth=1 kernel
  - cd kernel && bash build_kernel.sh beryllium $BOT_TOKEN -c
